### ISSUE TITLE
Link to data file for pandas episode missing

### ISSUE THREAD

**Issue by libcce** [datacarpentry/python-socialsci#101]
The link to the data file being used for this episode https://datacarpentry.org/python-socialsci/08-Pandas/index.html (SN7577.tab) is missing. Also, consider using requests:

import pandas as pd
import io
import requests
url="https://raw.githubusercontent.com/datacarpentry/python-socialsci/gh-pages/data/SN7577.tab"
s=requests.get(url).content
c=pd.read_csv(io.StringIO(s.decode('utf-8')), sep='\t')

Provide brief info on the dataset being used in the episode or in setup.

**Comment by blakeflei** [comment]
@libcce - I love the idea of making the code work out of the box, but maybe I missed a setup step somewhere. It seems like a similar approach was used in the previous lesson [https://datacarpentry.org/python-socialsci/07-json/index.html](https://datacarpentry.org/python-socialsci/07-json/index.html) (i.e. SAFI.json) Are you thinking re-address all the lessons? 

For consideration: for pandas version 0.19.2 or greater, urls can be passed directly:
```
import pandas as pd

url="https://raw.githubusercontent.com/datacarpentry/python-socialsci/gh-pages/data/SN7577.tab"
c=pd.read_csv(url, sep='\t')
```

Link to [Pandas read_csv docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html):

> **filepath_or_bufferstr : path object or file-like object**
>    Any valid string path is acceptable. The string could be a URL. Valid URL schemes include http, ftp, s3, and file. For file URLs, a host is expected. A local file could be: file://localhost/path/to/table.csv.

**Comment by libcce** [comment]
@blakeflei this was a while ago, I'm having trouble what I was thinking 😃 Your improvement with pandas version 0.19.2 or greater looks like the better path.
