### ISSUE TITLE
Suggest JSON viewer for JSON episodes

### ISSUE THREAD

**Issue by libcce** [datacarpentry/python-socialsci#103]
Suggest JSON viewer for JSON episodes to help learners visualize what JSON looks like in a browser.

To view JSON in your browser in a readable way:
https://chrome.google.com/webstore/search/json?hl=en-US
Include other options?

Example:
https://api.crossref.org/works/10.1037/0003-066X.59.1.29/agency

**Comment by annajiat** [comment]
Thank you @libcce for bringing this up and your excellent suggestions.

These as well as additional viewing options have been added through https://github.com/datacarpentry/python-socialsci/pull/133

If additional changes are required, please feel free to submit PR or post issues.
