### ISSUE TITLE
Add information about SAFI dataset in processing data from a file episode

### ISSUE THREAD

**Issue by libcce** [datacarpentry/python-socialsci#105]
Add to processing data from a file episode information about the dataset being used:

SAFI (Studying African Farmer-Led Irrigation) 
Project looking at farming and irrigation methods
Survey data from interviews in 2016-17
Households and ag in Tanzania and Mozambique. 
Data includes household features, ag practices, assets, and details about the household members

**Comment by kerchner** [comment]
Note that the lack of the description file causes a broken link in _episodes/05-processing-data-from-file.md as it includes a link to https://datacarpentry.org/python-socialsci/data/SAFI_results_desc.txt which doesn't exist yet.
