### ISSUE TITLE
Python basics

### ISSUE THREAD

**Issue by YangDawu** [datacarpentry/python-socialsci#108]
hi, i'm new to jupyter and to python. i ran across this material as i was wading thru stuff on a Edx Python for Data Science course (exploratory, newbie, see what's happening auditor). so i decided to explore more. your course looks structured and useful for people like me (trying to understand "big data").

anyway, your basics lesson had me befuddled in two places:

1. "Imagine you are considering different ways of representing a boolean value..."
  i couldn't figure out what you wanted, even given your answer
2. We can index lists the same way we indexed strings before or using a boolean list of the same length.
  your answer generated an error message--and had my head spinning
3. there was a typo of "of" instead of "or" somewhere in the text, but i've lost the place--maybe you can find it.

**Comment by OmaymaS** [comment]
For point 2:
> We can index lists the same way we indexed strings before or using a boolean list of the same length.

I think it would be clearer with a modification like:

We can index lists in different ways:
1. the same way was we indexed strings before in section [...].
2. using a boolean list of the same length as shown in section [...].

Using the number list defined above `num_list `, complete the cold below:
1. create a boolean list `is_odd ` of the same length of `num_list` with `True` at the position of the odd values.
2. use `is_odd ` to index `num_list` and assign the result to `odd_from_list`.
3. index `num_list` to return the last value and assign to `last_num_in_list`.

**Comment by Kilatsat** [comment]
For point 2:
The issue here is not the clarity of the instructions, but that the solution produces an error message when executed.
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-563a80bb5974> in <module>
      1 num_list = [4,5,6,11]
      2 is_odd = [False, True, False, True]
----> 3 odd_from_list = num_list[is_odd]

TypeError: list indices must be integers or slices, not list
```

I searched for similar examples found this: https://stackoverflow.com/questions/53527850/how-to-mask-a-list-using-boolean-values-from-another-list/53527895#53527895

For point 3:
The typo (`of` instead of `or`) is in the "Strings" section
```
If you need to use quotes as part of your string you can arbitrarily use either single of double quotes to indicate the start and end of the string.
```

**Comment by eldobbins** [comment]
These errors are still in the lesson, and I can verify the error message - even if I cut and paste the solution.  I think maybe the idea of Boolean subsetting of lists came from some of the things that Pandas can do, but lists can't do that.  That exercise should be removed.

**Comment by annajiat** [comment]
Thank you @YangDawu  and @eldobbins for elaborating the issues
Thank you @OmaymaS, @Kilatsat, @evebohnett, and @kevswanberg for ideas about the new solutions
