### ISSUE TITLE
June 2019 Lesson Release checklist

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/python-socialsci#109]
If your Maintainer team has decided not to participate in the [June 2019 lesson release](https://carpentries.topicbox.com/groups/maintainers/T61c75ac1a8a89538/timeline-and-process-for-june-lesson-release), please close this issue.

To have this lesson included in the 18 June 2019 release, please confirm that the following items are true:

- [ ] Example code chunks run as expected
- [ ] Challenges / exercises run as expected
- [ ] Challenge / exercise solutions are correct
- [ ] Call out boxes (exercises, discussions, tips, etc) render correctly
- [ ] A schedule appears on the lesson homepage (e.g. not “00:00”)
- [ ] Each episode includes learning objectives
- [ ] Each episode includes questions
- [ ] Each episode includes key points
- [ ] Setup instructions are up-to-date, correct, clear, and complete
- [ ] File structure is clean (e.g. delete deprecated files, insure filenames are consistent)
- [ ] Some Instructor notes are provided
- [ ] Lesson links work as expected

When all checkboxes above are completed, this lesson will be added to the 18 June lesson release. Please leave a comment on carpentries/lesson-infrastructure#26 or contact Erin Becker with questions (ebecker@carpentries.org).

**Comment by katrintirok** [comment]
Hi @sechilds and @gboushey, is there are plan for another release in June for this lesson? I am keen to fix some issues, but it would be good to know whether there are priorities.
I think there are a lot of open ends at the moment. I was teaching this lesson a few times, but with only a subset of the episodes, and only using the SAFI data and the pandas library for data exploration. Maybe we could make a minimum lesson that includes the same concepts as in the R lesson and then have other episodes (like the JSON one etc) as optional episodes at the end of the lesson.

**Comment by ErinBecker** [comment]
Hi @katrintirok and thanks for your interest in improving these lessons. I haven't heard from @sechilds and @gboushey about whether they want to include this lesson in the June release. So I'm going to go ahead and provisionally close this issue under the assumption that they are opting out of this release. @sechilds @gboushey - if you are interested in participating in the release, please go ahead and re-open this issue. Thanks!
