### ISSUE TITLE
add output cells

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/python-socialsci#11]
For each input chunk of code, show the output that will be produced. This will help the learners and the instructors to know that they are getting the expected output. 

Output code should be marked with `.output:` as described [here](http://swcarpentry.github.io/lesson-example/04-formatting/index.html).

**Comment by gboushey** [comment]
For SWC tutorials, Is there any preference or convention for using print() rather than typing the variable name or method name that provides output as the last line in the interactive shell or jupyter notebook?

**Comment by ErinBecker** [comment]
@gboushey I haven't taught Python for SWC, but my experience in teaching R for DC and SWC is that, even when not strictly necessary, the SWC/DC convention is to use an explicit print or return statement. This would serve to make the lessons more easily usable for learners not working with Jupyter notebooks.

**Comment by gboushey** [comment]
sounds good.  I'll take this one on. I'll add print statements to generate output where they aren't present to keep it consistent.

**Comment by sechilds** [comment]
Excellent. Thank you.

**Comment by gboushey** [comment]
- [x] chapter 2
- [x] chapter 3
- [x] chapter 4
- [x] chapter 5
- [] chapter 6
- [] chapter 7
- [] chapter 8
- [] chapter 9
- [] chapter 10
- [] chapter 11
- [] chapter 12
- [] chapter 13

**Comment by sechilds** [comment]
Closed by pull request #55.

See issues #56 and #57 about remaining output issues.

Thanks @gboushey
