### ISSUE TITLE
introduce python syntax highlighting

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/python-socialsci#12]
Code chunks should have the tag

`.language-python` 

as described [here](http://swcarpentry.github.io/lesson-example/04-formatting/index.html). This will make the code show up with standard Python color coding and other standard aesthetics.

**Comment by gboushey** [comment]
code chunks currently use .python rather than .language_python.  are we looking to change these tags, or just find what code chunks are currently not tagged as python code?

**Comment by ErinBecker** [comment]
@gboushey  I believe it should be changed to .language_python to enable the new syntax highlighting feature of the lesson template.

**Comment by ErinBecker** [comment]
Thanks @sechilds. This can be closed.
