### ISSUE TITLE
SN7577i_a.csv and SN7577i_b.csv are missing

### ISSUE THREAD

**Issue by eldobbins** [datacarpentry/python-socialsci#125]
Hi;

The episode [Joining Pandas Dataframes](https://datacarpentry.org/python-socialsci/11-joins/index.html) references 2 files that are described as "cut down versions of the SN7577 dataset to make the displays more manageable".  These files are called SN7577i_a.csv and SN7577i_b.csv.  However, these files are not included in the [set-up](https://datacarpentry.org/python-socialsci/setup.html).

Actually, it looks like there is a whole series of these files - a, b, aa, bb, c, and d.  Are those available elsewhere?

Liz

**Comment by annajiat** [comment]
Yes, [here](https://github.com/datacarpentry/python-socialsci/tree/gh-pages/data)

**Comment by bmg-pcl** [comment]
Submitted [PR127 ](https://github.com/datacarpentry/python-socialsci/pull/127 ) to add instructions to download the datafiles.
