### ISSUE TITLE
Replace file.open() and file.close() in lesson 5

### ISSUE THREAD

**Issue by akshayparopkari** [datacarpentry/python-socialsci#132]
Hi,

While teaching this lesson, we encountered a confusing bit of code in lesson 5. The lesson teaches `file.open()` and `file.close()` to process data from file. However, using the `with` statement is a cleaner and safer way to accomplish the same task. Additionally, `with` statement conforms with PEP and more information can be found [here](https://www.pythonforbeginners.com/files/with-statement-in-python)

As an example, the first code block in lesson 5 is -
```
filename = "SAFI_results.csv"
f = open(filename, "r")    # open the file whose name is in filename, the 'r' means we want to read from the file
                           # the open function returns what is called a file handle. we use this to refer to the file
for line in f:             # We use a for loop to iterate through the file one line at a time.
    print(line)            # we simply print the line

f.close()
```

can be replaced with -
```
filename = "SAFI_results.csv"
with open(filename, "r") as f:    # open the file whose name is in filename, the 'r' means we want to read from the file and the open function returns what is called a file handle. we use this to refer to the file
for line in f:                                # We use a for loop to iterate through the file one line at a time.
    print(line)                              # we simply print the line
```

Thanks!

**Comment by akshayparopkari** [comment]
Linking the (lesson)[https://datacarpentry.org/python-socialsci/05-processing-data-from-file/index.html] for convenience.

**Comment by tobyhodges** [comment]
I think this may be addressed by #124

**Comment by akshayparopkari** [comment]
Yes, merging #124 would fix it 👍
Thanks, @tobyhodges

**Comment by akshayparopkari** [comment]
Closing this issue
See #124 for more details
