### ISSUE TITLE
No jumplinks for section headings

### ISSUE THREAD

**Issue by brownsarahm** [datacarpentry/python-socialsci#172]
This lesson's rendered site doesn't have jumplinks on the sections headings as other lessons do.  

It's true on multiple pages of this lesson.

**Comment by annajiat** [comment]
@brownsarahm 
Thank you for noticing

@zkamvar 
We need to update style for this lesson so that jump lists (anchors for different sections) becomes automatically available for different levels of headings.

**Comment by zkamvar** [comment]
This is going to be fixed in tomorrow, so I'm going to close this (see #187)
