### ISSUE TITLE
pandas print(dataframe) vs dataframe in jupyter

### ISSUE THREAD

**Issue by gboushey** [datacarpentry/python-socialsci#33]
Several chapters (8-12) display pandas dataframes.  The current approach is to type the dataframe name without the print() method, allowing the default jupyter graphical (tab) rendering of a dataframe. Other SWC/CD tutorials often rely on the print(dataframe) approach, which is unformatted but will work outside jupyter at the python interactive shell. 

Options are 1) use print, 2) use the jupyter default rendering of a dataframe, 3) both. If we display the dataframe through jupyter without using print, I believe we'll need to do screen captures and format an image, since I don't think this can be rendered through the .output tag.

**Comment by katrintirok** [comment]
I don't see this as a problem, in the basics python episode the difference between using print() or not using it is explained and practiced. When using IPython or another Python console, one can also return content of an object by only recalling the name (without print).

It appears that there was a merged PR addressing this issue in April last year, making this issue obsolete. Can old issues be closed, to make it easier to find the issues that need attention, especially towards the next lesson release.

**Comment by annajiat** [comment]
Looks like the issue has been addressed but not closed.
Thank you @gboushey @PeterSmyth12  @katrintirok
