### ISSUE TITLE
Update index.md with introduction and prerequisites

### ISSUE THREAD

**Issue by sechilds** [datacarpentry/python-socialsci#38]
The `index.md` file has two **FIXME** indicators -- the first is an introduction and the second is the list of prerequisites.

A good starting point for this would be the python ecology lesson: [https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/index.md](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/index.md)

Maintainer's names need to be added as well.

**Comment by brownsarahm** [comment]
Should also reference [the data reference page](http://www.datacarpentry.org/socialsci-workshop/data/) for more context.

**Comment by annajiat** [comment]
Thank you @sechilds , @brownsarahm , @Tadigutsah , @katrintirok 

Under [pre-requisites](https://datacarpentry.org/python-socialsci/), [included](https://github.com/datacarpentry/python-socialsci/commit/0999be04345faca4ba880779f17285b294e1a67e) guidance on downloading data files listed in the [setup](https://datacarpentry.org/python-socialsci/setup.html).

Hopefully that takes care of the last of the issues. If there is any thing else, please feel free to open an issue.
