### ISSUE TITLE
Add key points for episode 3 - control structures

### ISSUE THREAD

**Issue by sechilds** [datacarpentry/python-socialsci#41]
Episode 3 is missing key points and currently only has placeholder text.

**Comment by PeterSmyth12** [comment]
Key points for 03-control-structures

- "Most programs will require 'Loops' and 'Branching' constructs."
- "The `if` `elif` `else` statements allow for branching in code."
- "The `for ` and `while statements allow for looping through sections of code"
- "The programmer must provide a condition which will end a `while` loop."
