### ISSUE TITLE
say what Jupyter stands for and give links

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/python-socialsci#5]
In [this episode](http://www.datacarpentry.org/python-socialsci/01-introduction/) there is a mention of how Jupyter is a successor to IPython that can handle more languages than just Python. Would be good here to say what Jupyter stands for and also give a link back to the Jupyter project.

**Comment by yeemey** [comment]
I can work on this!

**Comment by sechilds** [comment]
Great! Thanks.
