### ISSUE TITLE
JSON lesson

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/python-socialsci#54]
Teaching about JSON is valuable, but I'm not sure if there is the time to properly introduce and teach it here. It adds a new concept and cognitive overhead to introduce the JSON file format part way through. It is introduced in OpenRefine, so this could build on that, but we'd have to make sure to use the connection. This might be one that we don't include now, and come back to later.

**Comment by eldobbins** [comment]
If this is removed, then discussion of dictionaries should perhaps be placed after the introduction of lists.  

As it is, dictionaries aren't discussed much.  The JSON episode includes the statement "In the last episode we introduced the dictionary object."  But the previous lesson is Dates and Times and does not include any dictionaries, so I'm not sure what is referenced there.

**Comment by annajiat** [comment]
- The JSON lesson has evolved more with further explanations and specially the visualizations which might be helpful in easing the cognitive load.
- It is possible that the python lesson is taught individually, without the OpenRefine lesson, so, without JSON, the lesson may seem incomplete. Instructors may choose to skip parts of the episode as they see fit.
- JSON is used widely on the web, so we may choose to keep it.

**Comment by annajiat** [comment]
Thank you @eldobbins
The reference has been corrected in #146
