### ISSUE TITLE
mention keyboard shortcut for running cells

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/python-socialsci#6]
In the introduction episode there is this sentence:

>> To interpret the code in a cell you need to click the run button in the toolbar or from the Cell menu option. At which point all of the code in that cell will be executed.

It would be good to mention here the keyboard shortcut(s) for running cells. These are probably different between Mac and PC.

**Comment by yeemey** [comment]
will add shortcut for Mac.

**Comment by sechilds** [comment]
The keyboard shortcuts are the same across Mac and PC - shift + enter (or ctrl + enter).  This has been resolved by #26 and #30
