### ISSUE TITLE
plots are only on random data

### ISSUE THREAD

**Issue by brownsarahm** [datacarpentry/python-socialsci#72]
Introducing random data generation to teach plotting instead of working with the data doesn't seem like the best strategy.  We found the following plots to be useful examples.

Numerical histogram:
df['C06_rooms'].plot(kind='hist')

Categorical histogram:
df.groupby('C02_respondent_wall_type')['C01_respondent_roof_type'].hist(stacked=False)

Scatter:
df.plot.scatter('gps:Latitude','gps:Longitude',c='gps:Altitude',colormap='jet')

2 exercises
df.plot.scatter('A11_years_farm','B16_years_liv',c='C05_buildings_in_compound',colormap='jet')
challenge
df.groupby('C02_respondent_wall_type')['C06_rooms'].mean().plot(kind='bar')

**Comment by annajiat** [comment]
Fixed by #159 
Thank you @brownsarahm
