### ISSUE TITLE
if..else used in episode 02 before concept introduced in episode 03

### ISSUE THREAD

**Issue by katrintirok** [datacarpentry/python-socialsci#86]
if..else is used with code as well as in exercise in episode 02 under paragraph 'Basic Python data types', where boolean data type is introduced. But proper intro to if..else statements only comes in episode 03.

Solution: change teaching and exercise around boolean data types in episode 02

**Comment by sechilds** [comment]
PR #91 also addresses this issue. Once that one is merge, we can close it.

**Comment by annajiat** [comment]
Closing the issue as  #91 has been merged.
