### ISSUE TITLE
Formatting broken on reference page

### ISSUE THREAD

**Issue by brownsarahm** [datacarpentry/python-socialsci#88]
this may be due to a styles change

**Comment by sechilds** [comment]
I was running in to this problem today myself, but I think it has been fixed by the styles change. The page online looks ok.

@brownsarahm can you also check to see if it is OK now?

**Comment by annajiat** [comment]
Thank you @brownsarahm for reporting the issue and @sechilds for reviewing. Looks like it is fixed now. Closing the issue. Please feel free to reopen if you find any issues.
