### ISSUE TITLE
list of typos - WIP

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/python-socialsci#9]
The following is a list of typos that I've found in this lesson:

# Episode 2 - Python basics
>> When you run cells of code the **out put** is displayed immediately below the cell. In general this is convenient. The output is associated with the cell that produced it and remains a part of the notebook. So if you copy or move the notebook the output stays with the code.

should be "output"

>>However lots of output can mke the notebook look cluttered and more difficult to move around. So there is an option available from the cell menu item to ‘toggle’ or ‘clear’ the output associated either with an individual **cel** or all cells in the notebook.

should be "cell"

>> type()

should be `type()`
There are other examples of this in other episodes. Would be good to do a search for "()" to find them.

# Episode 3: Python control structures
>> The basic format of the if statement is:
if expression : statement 1 statement 2 … statement n next statement

I think there are some missing new lines here.

**Comment by yeemey** [comment]
More typos for Episode 2. Also, is "datatype" correct? I think it [should be "data type"](https://docs.python.org/3/library/datatypes.html) and noted them below.

# Episode 2: Python basics
> ## New cells
>From the insert menu item you can insert a new cell anywhere in the notebook either above or below the current cell. You can also **us** the + button on the toolbar to insert a new cell below.

should be "use"

> ## Variables and Types
>All variables have a data type associated with them. The **datatype** is an indication of the type of data contained in a variable.

should be "data type"

> ## Simple arithmetic operations
>For now we will stick with the numeric types and do some arithmetic.
>
>All of the usual arithmetic operators are available.
>
>In the examples below we also introduce the Python comment symbol ‘#’. Anything to the right of the ‘#’ symbol is treated as a comment. To a large extent using **markdown** cells in a notebook reduces the need for comments in the code, but occasionally they can be useful. - Don’t **over do** them.

should be "Markdown" and "overdo"

>We also make use of the built-in **'print()'** function.
>
>We need to use the **print** function because by default only the last output from a cell is displayed in the output cell.
>
>The first call to the **print** function is passed four different parameters, each **seperated** by a comma. A string “a = “ followed by a followed by the string “b = “ and then the variable b.
>
>The output is what you would probably have guessed at.

>
>All of the other calls to **print** are only passed a single parameter. Although it may look like 2 or 3, the expressions are evaluated first and it is only the single result which is seen as the parameter value and printed.

should be `print()` and "separated"

> ## Using built-in functions
>Python has a reasonable number of built-in functions. You can find a complete list in the **offical** documentation**.**
>
>Additional functions are provided by 3rd party packages which we will look at later on.
>
>For any function, a common question to ask **is; W**what parameters does this function take?

should be "official", missing period, "is what"

> ## Getting Help for Python
>
>There is a great deal of Python help and information as well as code examples **avaialble** from the Internet. 

should be "available"

>A couple of things you may need to **wary** of: There are currently 2 versions of Python in use**,** in most cases code examples will both in either but there are some exceptions.

should be "be wary" or "be aware", "; in most cases code examples will work"

> ## **Datatype** and how Python uses them
> ###Changing **datatypes**
>The **datatype** of a variable is assigned when you give a variable a value as we did above. If you re-assign the value of a variable, you can change the data type.
>
>In some **circimstances** explicitly converting a **datatype** makes no sense; you cannot change a string with alphabetic characters into a number.

should be "data type", "circumstances"

> ## Strings
>A string is a simple **datatype** which holds a sequence of characters.
>
>Strings are placed in quotes when they are being assigned, but the quotes don’t count as part of >the string value.
>
>If you need to use quotes as part of your string you can **arbitarily** use either single of double **qoutes** to indicate the start and end of the string.

should be "data type", "arbitrarily", "quotes"

> ## String functions
>
>If you need to refer to a specific element (character** )** in a string, you can do so by specifying the index of the character in ‘[]’ you can **aslo** use indexing to select a substring of the string

should be "also"

> ## Basic Python **datatypes**
>So far we have seen three basic Python data types; Integer, Float and String. There is another basic **datatype;** Boolean. Boolean variables can only have the values of either True or False. (Remember, **python is case sensitive**, so be careful of your spelling.) We can define variables to be of type boolean by setting their value accordingly.

should be "Python is case-sensitive" (This typo made me laugh :) )

> ## Structured **datatypes**
>A structured **datatype** is a **datatype** which is made up of some combination of the base **datatypes** in a well defined but potentially arbitrarily complex ways. 

should be "data type"

> ## Key Points
>The Jupyter **environnment** can be used to write code segments and display results
>
>**Datatypes** in **Pyhthon** are implicit based on variable values
>
>Basic **datatypes** are Integer, Float, String and Boolean
>
>Lists and Dictionaries are structured **datatypes**

should be "environment", "Python", "data type"

**Comment by sechilds** [comment]
# Episode 4 - Reusable Code

>## Exercise
>**vWrite** a function definition to calculate the volume of a cuboid. The function will use three parameters ‘H’, ‘W’ and ‘L’ and return the volume.
>
>Supposing that in addition to the volume I also wanted to calculate the surface area and the sum of all of the edges. Would I (or should I) have three seperate functions or could I write a single function to provide all three values together?

Get rid of the extra 'v' before Write.

**Comment by katrintirok** [comment]
I went through all episodes and fixed typos and formatting errors I could find (see #84), everything noted in this issue should be addressed now. I suggest that this issue can be closed, if the pull request I opened is ok and can be merged. For newly found typos perhaps a new issue can be opened.

**Comment by annajiat** [comment]
Thank you @ErinBecker , @sechilds , @tg340 , @yeemey , @katrintirok .

Check and fixed remaining issues through this [commit](https://github.com/datacarpentry/python-socialsci/commit/60692a455054e165706aa47ed6f5087455a5341f).

All of the mentioned issues should be fixed now. In case anything is remaining or something new comes up, please feel free to open an issue.
