### ISSUE TITLE
Links broken on python-socialsci/index.md 

### ISSUE THREAD

**Issue by craigboman** [datacarpentry/python-socialsci#94]
There are some broken links on index.md page that need to be updated. Specifically the setup and instructor guide links are broken. https://github.com/datacarpentry/python-socialsci/blob/gh-pages/index.md

**Comment by annajiat** [comment]
Thank you @craigboman for reporting the issue. Looks like it is fixed now. Closing the issue. Please feel free to reopen if the find any issues.
