### ISSUE TITLE
Explain diff between method, function

### ISSUE THREAD

**Issue by libcce** [datacarpentry/python-socialsci#97]
In episode 2 (https://github.com/datacarpentry/python-socialsci/edit/gh-pages/_episodes/02-basics.md) there was confusion in the workshop we ran regarding what is a method vs a function, particularly with regard to void functions which we see after using print(dir(mystring)).

**Comment by annajiat** [comment]
Thank you @libcce for bringing this up. 

A method is a function that “belongs to” an object. In Python, the term method is not unique to class instances: other object types can have methods as well. For example, list objects have methods called append, insert, remove, sort, and so on.

Source: https://docs.python.org/3/tutorial/classes.html
